### PR TITLE
fix: process only entry css file

### LINKED ISSUE #122: Unsupported value errors on Expo SDK 55 canary
### What happened?

I upgraded a project to SDK 55 canary and my terminal is full of Uniwind errors.

```

| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"fadeInUp"},"duration":{"type":"milliseconds","value":200},"timingFunction":{"type":"ease-out"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className container
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"fadeInUp"},"duration":{"type":"milliseconds","value":200},"timingFunction":{"type":"ease-out"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className content
| 
| Uniwind Error [CSS Processor] - Unsupported value type - "filters" for className bg
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"data-expo-log-backdrop-fade-in"},"duration":{"type":"milliseconds","value":150},"timingFunction":{"type":"ease-out"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className bg
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"fadeOut"},"duration":{"type":"milliseconds","value":150},"timingFunction":{"type":"ease-in"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className bgExit
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"fadeOutUp"},"duration":{"type":"milliseconds","value":150},"timingFunction":{"type":"ease-in"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className containerExit
| 
| Uniwind Error [CSS Processor] - Unsupported value type - "filters" for className headerBlur
| 
| Uniwind Error - Failed to create virtual js
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"fadeInUp"},"duration":{"type":"milliseconds","value":200},"timingFunction":{"type":"ease-out"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className container
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"fadeInUp"},"duration":{"type":"milliseconds","value":200},"timingFunction":{"type":"ease-out"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className content
| 
| Uniwind Error [CSS Processor] - Unsupported value type - "filters" for className bg
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"data-expo-log-backdrop-fade-in"},"duration":{"type":"milliseconds","value":150},"timingFunction":{"type":"ease-out"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className bg
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"fadeOut"},"duration":{"type":"milliseconds","value":150},"timingFunction":{"type":"ease-in"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className bgExit
| 
| Uniwind Error [CSS Processor] - Unsupported value - {"name":{"type":"ident","value":"fadeOutUp"},"duration":{"type":"milliseconds","value":150},"timingFunction":{"type":"ease-in"},"iterationCount":{"type":"number","value":1},"direction":"normal","playState":"running","delay":{"type":"seconds","value":0},"fillMode":"forwards","timeline":{"type":"auto"}} for className containerExit
| 
| Uniwind Error [CSS Processor] - Unsupported value type - "filters" for className headerBlur
| 
| Uniwind Error - Failed to create virtual js
| 
| Uniwind Error - Failed to create virtual js
```

### Steps to Reproduce

1. Bootstrap an expo project
2. npx expo install expo@canary --fix

### Snack or Repository Link

https://github.com/focux/uniwind-repro

### Uniwind version

RC 7

### React Native Version

0.82.1

### Platforms

iOS

### Expo

Yes

### Additional information

- [x] I've searched for [similar issues in this repository](https://github.com/Unistyles-OSS/uniwind/issues) and found none

### PR DESCRIPTION
**Pull request by Brentlok**
fixes #122

### CODE REVIEW

File: packages/uniwind/src/metro/compileVirtual.ts [hunk 1]
```diff
@@ -9,18 +10,27 @@ import { serializeJSObject } from './utils'
...
         onDependency: () => void 0,
     })
-    const tailwindCSS = compiler.build(candidates)
+    const scanner = new Scanner({
+        sources: [
+            ...compiler.sources,
+            {
+                negated: false,
+                pattern: '**/*',
+                base: path.dirname(cssPath),
```
Comment (rubenamorim) [inline packages/uniwind/src/metro/compileVirtual.ts]: @Brentlok I believe this introduced a bug when the CSS input file is not in the root or src directory tree, such as:

```
app
   - ....
styles
   - global.css
``` 

Metro config:

```js
const uniwindConfig = withUniwindConfig(config, {
  cssEntryFile: "./styles/global.css",
});

module.exports = uniwindConfig;
```

Based on my brief debugging with limited context, changing this to `process.cwd()` fixes the issue 🙈

Comment (rubenamorim) [reply packages/uniwind/src/metro/compileVirtual.ts]: Placing the CSS input file in the root directory significantly increases build time, likely due to scanning the `node_modules` and hidden folders 😬
